/// Unified typed error enum for SpacetimeDB reducers.
///
/// Generated by the typed-errors scanner.
/// Replace all `Result<(), String>` with `Result<(), ReducerError>`
/// and replace string-based `Err(...)` with typed variants.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReducerError {
    /// `API key not found`
    APIKeyNotFound,
    /// `Agent not registered`
    AgentNotRegistered,
    /// `Cannot block task with status: {}`
    CannotBlockTaskWithStatus,
    /// `Cannot claim — dependency '{}' ({}) is not done (status: {})`
    CannotClaimDependencyIsNotDoneStatus,
    /// `Cannot complete task with status: {}`
    CannotCompleteTaskWithStatus,
    /// `Cannot relate a task to itself`
    CannotRelateATaskToItself,
    /// `Cannot split task with status: {}`
    CannotSplitTaskWithStatus,
    /// `Cannot unclaim task with status: {}`
    CannotUnclaimTaskWithStatus,
    /// `Checklist item not found`
    ChecklistItemNotFound,
    /// `Comment not found`
    CommentNotFound,
    /// `Dependency task '{}' not found`
    DependencyTaskNotFound,
    /// `Invalid relation type: {}. Valid: {}`
    InvalidRelationTypeValid,
    /// `Issue link not found`
    IssueLinkNotFound,
    /// `Key not found`
    KeyNotFound,
    /// `Label assignment not found`
    LabelAssignmentNotFound,
    /// `Label not found`
    LabelNotFound,
    /// `Label not found: {}`
    LabelNotFound1,
    /// `Migration '{}' already applied`
    MigrationAlreadyApplied,
    /// `Must specify at least one child title`
    MustSpecifyAtLeastOneChildTitle,
    /// `Parent task not found`
    ParentTaskNotFound,
    /// `Project '{}' already exists`
    ProjectAlreadyExists,
    /// `Project '{}' not found`
    ProjectNotFound,
    /// `Project id (repo slug) is required`
    ProjectIdRepoSlugIsRequired,
    /// `Related task not found`
    RelatedTaskNotFound,
    /// `Relation already exists`
    RelationAlreadyExists,
    /// `Rule not found`
    RuleNotFound,
    /// `Task is not available (current status: {})`
    TaskIsNotAvailableCurrentStatus,
    /// `Task not found`
    TaskNotFound,
    /// `Task not found: {}`
    TaskNotFound1,
    /// `Template not found`
    TemplateNotFound,
    /// `Webhook not found`
    WebhookNotFound,
    /// `due_by={}`
    DueBy,
    /// `est={}h spent={}h`
    EstHSpentH,
    /// `position={}`
    Position,
    /// `sprint={}`
    Sprint,
    /// `task_ids and label_ids must be non-empty`
    TaskIdsAndLabelIdsMustBeNonEmpty,
    /// `template:{}`
    Template,
}

impl std::fmt::Display for ReducerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<"_">) -> std::fmt::Result {
        match self {
            Self::APIKeyNotFound => write!(f, "API key not found"),
            Self::AgentNotRegistered => write!(f, "Agent not registered"),
            Self::CannotBlockTaskWithStatus => write!(f, "Cannot block task with status: {}"),
            Self::CannotClaimDependencyIsNotDoneStatus => write!(f, "Cannot claim — dependency '{}' ({}) is not done (status: {})"),
            Self::CannotCompleteTaskWithStatus => write!(f, "Cannot complete task with status: {}"),
            Self::CannotRelateATaskToItself => write!(f, "Cannot relate a task to itself"),
            Self::CannotSplitTaskWithStatus => write!(f, "Cannot split task with status: {}"),
            Self::CannotUnclaimTaskWithStatus => write!(f, "Cannot unclaim task with status: {}"),
            Self::ChecklistItemNotFound => write!(f, "Checklist item not found"),
            Self::CommentNotFound => write!(f, "Comment not found"),
            Self::DependencyTaskNotFound => write!(f, "Dependency task '{}' not found"),
            Self::DueBy => write!(f, "due_by={}"),
            Self::EstHSpentH => write!(f, "est={}h spent={}h"),
            Self::InvalidRelationTypeValid => write!(f, "Invalid relation type: {}. Valid: {}"),
            Self::IssueLinkNotFound => write!(f, "Issue link not found"),
            Self::KeyNotFound => write!(f, "Key not found"),
            Self::LabelAssignmentNotFound => write!(f, "Label assignment not found"),
            Self::LabelNotFound => write!(f, "Label not found"),
            Self::LabelNotFound1 => write!(f, "Label not found: {}"),
            Self::MigrationAlreadyApplied => write!(f, "Migration '{}' already applied"),
            Self::MustSpecifyAtLeastOneChildTitle => write!(f, "Must specify at least one child title"),
            Self::ParentTaskNotFound => write!(f, "Parent task not found"),
            Self::Position => write!(f, "position={}"),
            Self::ProjectAlreadyExists => write!(f, "Project '{}' already exists"),
            Self::ProjectIdRepoSlugIsRequired => write!(f, "Project id (repo slug) is required"),
            Self::ProjectNotFound => write!(f, "Project '{}' not found"),
            Self::RelatedTaskNotFound => write!(f, "Related task not found"),
            Self::RelationAlreadyExists => write!(f, "Relation already exists"),
            Self::RuleNotFound => write!(f, "Rule not found"),
            Self::Sprint => write!(f, "sprint={}"),
            Self::TaskIdsAndLabelIdsMustBeNonEmpty => write!(f, "task_ids and label_ids must be non-empty"),
            Self::TaskIsNotAvailableCurrentStatus => write!(f, "Task is not available (current status: {})"),
            Self::TaskNotFound => write!(f, "Task not found"),
            Self::TaskNotFound1 => write!(f, "Task not found: {}"),
            Self::Template => write!(f, "template:{}"),
            Self::TemplateNotFound => write!(f, "Template not found"),
            Self::WebhookNotFound => write!(f, "Webhook not found"),
        }
    }
}

impl std::error::Error for ReducerError {}
