#!/usr/bin/env python3
"""Ultra-fast task fountain — runs in <3s, creates tasks for workers.

Only keeps the board healthy when tasks are running low.
Does NOT duplicate main scanner findings (unwraps, bare excepts, large files, etc.)
to prevent infinite task loops. The main scanner system (scanners/runner.py)
handles those on a longer interval with proper dedup.

Only scans a hardcoded set of known-good repos. No discover_repos overhead.
"""

import json
import os
import sys
import urllib.error
import urllib.request

API = os.environ.get("KANBAN_API", "http://localhost:8727")

# REPOS is a hardcoded list of repos that are fast to scan (<1s each)
REPOS = [
    "spacetimedb-kanban",
    "sample-repo-f",
    "sample-repo-r",
    "sample-repo-o",
    "sample-repo-m",
    "sample-repo-p",
    "sample-repo-n",
    "sample-repo-d",
    "sample-repo-e",
]

HOME = os.path.expanduser("~")

# Scanner registry — each is a function that returns findings
SCANNERS = []


def register(fn):
    SCANNERS.append(fn)
    return fn


def api_get(path: str):
    try:
        with urllib.request.urlopen(f"{API}{path}", timeout=5) as resp:
            return json.loads(resp.read().decode())
    except Exception:
        return None


def api_post(path: str, data: dict):
    try:
        body = json.dumps(data).encode()
        req = urllib.request.Request(f"{API}{path}", data=body, method="POST")
        req.add_header("Content-Type", "application/json")
        with urllib.request.urlopen(req, timeout=5) as resp:
            content = resp.read().decode()
            return json.loads(content) if content else {"status": "ok"}
    except Exception:
        return None


def fetch_existing_titles() -> set[str]:
    """Lightweight — only check available + inProgress (cheapest calls)."""
    existing = set()
    for status in ("available", "inProgress"):
        try:
            with urllib.request.urlopen(
                f"{API}/api/tasks?status={status}&limit=50", timeout=3
            ) as resp:
                tasks = json.loads(resp.read().decode())
                if tasks:
                    for t in tasks:
                        title = t.get("title", "")
                        if title:
                            existing.add(title.strip().lower())
        except Exception:
            pass
    return existing


def is_dup(title: str, existing: set[str]) -> bool:
    return title.strip().lower() in existing


# ── Scanner: Board health — keeps minimum task pool ──
# This is the ONLY scanner in the fountain. All other scanner types
# (unwraps, bare excepts, large files, test gaps, etc.) run via the
# main scanner system (scanners/runner.py) on a longer interval.
# Having duplicates here creates infinite task loops because the
# fountain runs every 60s while the main scanner dedup can't keep up.


@register
def scan_board_health(repo_name: str, repo_path: str) -> list[dict]:
    """Only create task if the board has fewer than 3 available tasks."""
    try:
        with urllib.request.urlopen(f"{API}/api/tasks?status=available") as resp:
            available = json.loads(resp.read().decode())
        if available and len(available) >= 3:
            return []  # Board healthy — don't create anything
    except Exception:
        pass

    # Board near-empty — create one generic task
    return [
        {
            "title": f"Review {repo_name} for actionable improvements",
            "description": (
                f"Auto-generated by task fountain. "
                f"Review {repo_name} and create concrete tasks as needed."
            ),
            "priority": 4,
        }
    ]


# ── Main ──


def run() -> int:
    """Run all scanners on all repos. Returns number of tasks created."""
    existing = fetch_existing_titles()

    import sys

    print(f"  existing={len(existing)} repos={len(REPOS)}", file=sys.stderr)

    created = 0
    for repo_name in REPOS:
        repo_path = os.path.join(HOME, repo_name)
        if not os.path.isdir(os.path.join(repo_path, ".git")):
            continue

        for scanner in SCANNERS:
            try:
                findings = scanner(repo_name, repo_path)
            except Exception:
                continue

            for f in findings:
                title = f["title"]
                if is_dup(title, existing):
                    continue
                result = api_post(
                    "/api/tasks",
                    {
                        "title": title,
                        "description": f.get("description", ""),
                        "priority": f.get("priority", 2),
                        "repo": repo_name,
                        "roadmap_item": "Scanner: task-fountain",
                    },
                )
                if result:
                    existing.add(title.strip().lower())
                    created += 1

    return created


if __name__ == "__main__":
    n = run()
    print(f"[fountain] Created {n} task(s)", file=sys.stderr)
    sys.exit(0)
