"""Typed error enum for string-based errors.

Generated by the typed-errors scanner.
Replace bare strings with typed variants.
"""

from __future__ import annotations

from enum import StrEnum


class AppError(StrEnum):
    ERROR_0 = "..."
    AGENT_NOT_FOUND = "Agent not found"
    INVALID_OR_MISSING_API_KEY = "Invalid or missing API key"
    NO_GITHUB_ISSUE_LINKED_TO_THIS_TASK = "No GitHub issue linked to this task"
    NO_LINK_FOUND_FOR_THIS_TASK = "No link found for this task"
    RULE_NOT_FOUND = "Rule not found"
    TASK_NOT_FOUND = "Task not found"
    TEMPLATE_NOT_FOUND = "Template not found"
    TEMPLATE_NOT_FOUND_AFTER_CREATION = "Template not found after creation"
    WEBHOOK_NOT_FOUND = "Webhook not found"
    ID_REPO_SLUG_IS_REQUIRED = "id (repo slug) is required"
    MESSAGE = "message"
    STRING = "string"
