// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddTaskReducer from "../add_task_reducer";
import BlockTaskReducer from "../block_task_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import CompleteTaskReducer from "../complete_task_reducer";
import DeleteTaskReducer from "../delete_task_reducer";
import SeedSampleTasksReducer from "../seed_sample_tasks_reducer";
import UnclaimTaskReducer from "../unclaim_task_reducer";
import UpdateTaskReducer from "../update_task_reducer";

export type AddTaskParams = __Infer<typeof AddTaskReducer>;
export type BlockTaskParams = __Infer<typeof BlockTaskReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CompleteTaskParams = __Infer<typeof CompleteTaskReducer>;
export type DeleteTaskParams = __Infer<typeof DeleteTaskReducer>;
export type SeedSampleTasksParams = __Infer<typeof SeedSampleTasksReducer>;
export type UnclaimTaskParams = __Infer<typeof UnclaimTaskReducer>;
export type UpdateTaskParams = __Infer<typeof UpdateTaskReducer>;

