// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddChecklistItemReducer from "../add_checklist_item_reducer";
import AddCommentReducer from "../add_comment_reducer";
import AddLabelReducer from "../add_label_reducer";
import AddLogReducer from "../add_log_reducer";
import AddTaskReducer from "../add_task_reducer";
import AddWebhookSubscriptionReducer from "../add_webhook_subscription_reducer";
import AgentHeartbeatReducer from "../agent_heartbeat_reducer";
import AssignLabelToTaskReducer from "../assign_label_to_task_reducer";
import BatchAssignLabelsReducer from "../batch_assign_labels_reducer";
import BatchUnassignLabelsReducer from "../batch_unassign_labels_reducer";
import BlockTaskReducer from "../block_task_reducer";
import BulkReorderTasksReducer from "../bulk_reorder_tasks_reducer";
import ClaimTaskReducer from "../claim_task_reducer";
import CompleteTaskReducer from "../complete_task_reducer";
import DeleteCommentReducer from "../delete_comment_reducer";
import DeleteTaskReducer from "../delete_task_reducer";
import LinkIssueReducer from "../link_issue_reducer";
import LogWebhookDeliveryReducer from "../log_webhook_delivery_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import RemoveChecklistItemReducer from "../remove_checklist_item_reducer";
import RemoveLabelReducer from "../remove_label_reducer";
import RemoveWebhookSubscriptionReducer from "../remove_webhook_subscription_reducer";
import ReorderChecklistItemsReducer from "../reorder_checklist_items_reducer";
import ReorderTaskReducer from "../reorder_task_reducer";
import SeedSampleTasksReducer from "../seed_sample_tasks_reducer";
import SetAgentCapabilitiesReducer from "../set_agent_capabilities_reducer";
import SetDependencyReducer from "../set_dependency_reducer";
import SetTaskScoreReducer from "../set_task_score_reducer";
import SetTaskSkillsReducer from "../set_task_skills_reducer";
import ToggleChecklistItemReducer from "../toggle_checklist_item_reducer";
import UnassignLabelFromTaskReducer from "../unassign_label_from_task_reducer";
import UnclaimTaskReducer from "../unclaim_task_reducer";
import UnlinkIssueReducer from "../unlink_issue_reducer";
import UpdateIssueLinkStatusReducer from "../update_issue_link_status_reducer";
import UpdateLabelReducer from "../update_label_reducer";
import UpdateTaskReducer from "../update_task_reducer";
import UpdateWebhookSubscriptionReducer from "../update_webhook_subscription_reducer";

export type AddChecklistItemParams = __Infer<typeof AddChecklistItemReducer>;
export type AddCommentParams = __Infer<typeof AddCommentReducer>;
export type AddLabelParams = __Infer<typeof AddLabelReducer>;
export type AddLogParams = __Infer<typeof AddLogReducer>;
export type AddTaskParams = __Infer<typeof AddTaskReducer>;
export type AddWebhookSubscriptionParams = __Infer<typeof AddWebhookSubscriptionReducer>;
export type AgentHeartbeatParams = __Infer<typeof AgentHeartbeatReducer>;
export type AssignLabelToTaskParams = __Infer<typeof AssignLabelToTaskReducer>;
export type BatchAssignLabelsParams = __Infer<typeof BatchAssignLabelsReducer>;
export type BatchUnassignLabelsParams = __Infer<typeof BatchUnassignLabelsReducer>;
export type BlockTaskParams = __Infer<typeof BlockTaskReducer>;
export type BulkReorderTasksParams = __Infer<typeof BulkReorderTasksReducer>;
export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CompleteTaskParams = __Infer<typeof CompleteTaskReducer>;
export type DeleteCommentParams = __Infer<typeof DeleteCommentReducer>;
export type DeleteTaskParams = __Infer<typeof DeleteTaskReducer>;
export type LinkIssueParams = __Infer<typeof LinkIssueReducer>;
export type LogWebhookDeliveryParams = __Infer<typeof LogWebhookDeliveryReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type RemoveChecklistItemParams = __Infer<typeof RemoveChecklistItemReducer>;
export type RemoveLabelParams = __Infer<typeof RemoveLabelReducer>;
export type RemoveWebhookSubscriptionParams = __Infer<typeof RemoveWebhookSubscriptionReducer>;
export type ReorderChecklistItemsParams = __Infer<typeof ReorderChecklistItemsReducer>;
export type ReorderTaskParams = __Infer<typeof ReorderTaskReducer>;
export type SeedSampleTasksParams = __Infer<typeof SeedSampleTasksReducer>;
export type SetAgentCapabilitiesParams = __Infer<typeof SetAgentCapabilitiesReducer>;
export type SetDependencyParams = __Infer<typeof SetDependencyReducer>;
export type SetTaskScoreParams = __Infer<typeof SetTaskScoreReducer>;
export type SetTaskSkillsParams = __Infer<typeof SetTaskSkillsReducer>;
export type ToggleChecklistItemParams = __Infer<typeof ToggleChecklistItemReducer>;
export type UnassignLabelFromTaskParams = __Infer<typeof UnassignLabelFromTaskReducer>;
export type UnclaimTaskParams = __Infer<typeof UnclaimTaskReducer>;
export type UnlinkIssueParams = __Infer<typeof UnlinkIssueReducer>;
export type UpdateIssueLinkStatusParams = __Infer<typeof UpdateIssueLinkStatusReducer>;
export type UpdateLabelParams = __Infer<typeof UpdateLabelReducer>;
export type UpdateTaskParams = __Infer<typeof UpdateTaskReducer>;
export type UpdateWebhookSubscriptionParams = __Infer<typeof UpdateWebhookSubscriptionReducer>;

