// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  keyHash: __t.string().name("key_hash"),
  name: __t.string(),
  repoScope: __t.option(__t.string()).name("repo_scope"),
  permissions: __t.string(),
  createdBy: __t.string().name("created_by"),
  createdAt: __t.u64().name("created_at"),
  lastUsedAt: __t.u64().name("last_used_at"),
  active: __t.bool(),
});
