// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  ruleId: __t.string().name("rule_id"),
  ruleName: __t.string().name("rule_name"),
  triggerEvent: __t.string().name("trigger_event"),
  taskId: __t.string().name("task_id"),
  actionType: __t.string().name("action_type"),
  result: __t.string(),
  errorMessage: __t.option(__t.string()).name("error_message"),
  firedAt: __t.u64().name("fired_at"),
});
