// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.1 (commit 07b52763c9da8d7cf79780db222fec1ffcb84070).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddChecklistItemReducer from "./add_checklist_item_reducer";
import AddCommentReducer from "./add_comment_reducer";
import AddLabelReducer from "./add_label_reducer";
import AddLogReducer from "./add_log_reducer";
import AddTaskReducer from "./add_task_reducer";
import AddWebhookSubscriptionReducer from "./add_webhook_subscription_reducer";
import AgentHeartbeatReducer from "./agent_heartbeat_reducer";
import AssignLabelToTaskReducer from "./assign_label_to_task_reducer";
import BatchAssignLabelsReducer from "./batch_assign_labels_reducer";
import BatchUnassignLabelsReducer from "./batch_unassign_labels_reducer";
import BlockTaskReducer from "./block_task_reducer";
import BulkReorderTasksReducer from "./bulk_reorder_tasks_reducer";
import ClaimTaskReducer from "./claim_task_reducer";
import CompleteTaskReducer from "./complete_task_reducer";
import DeleteCommentReducer from "./delete_comment_reducer";
import DeleteTaskReducer from "./delete_task_reducer";
import LinkIssueReducer from "./link_issue_reducer";
import LogWebhookDeliveryReducer from "./log_webhook_delivery_reducer";
import RegisterAgentReducer from "./register_agent_reducer";
import RemoveChecklistItemReducer from "./remove_checklist_item_reducer";
import RemoveLabelReducer from "./remove_label_reducer";
import RemoveWebhookSubscriptionReducer from "./remove_webhook_subscription_reducer";
import ReorderChecklistItemsReducer from "./reorder_checklist_items_reducer";
import ReorderTaskReducer from "./reorder_task_reducer";
import SeedSampleTasksReducer from "./seed_sample_tasks_reducer";
import SetAgentCapabilitiesReducer from "./set_agent_capabilities_reducer";
import SetDependencyReducer from "./set_dependency_reducer";
import SetTaskScoreReducer from "./set_task_score_reducer";
import SetTaskSkillsReducer from "./set_task_skills_reducer";
import ToggleChecklistItemReducer from "./toggle_checklist_item_reducer";
import UnassignLabelFromTaskReducer from "./unassign_label_from_task_reducer";
import UnclaimTaskReducer from "./unclaim_task_reducer";
import UnlinkIssueReducer from "./unlink_issue_reducer";
import UpdateIssueLinkStatusReducer from "./update_issue_link_status_reducer";
import UpdateLabelReducer from "./update_label_reducer";
import UpdateTaskReducer from "./update_task_reducer";
import UpdateWebhookSubscriptionReducer from "./update_webhook_subscription_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import IssueLinksRow from "./issue_links_table";
import KanbanLabelsRow from "./kanban_labels_table";
import SwarmAgentsRow from "./swarm_agents_table";
import TaskChecklistsRow from "./task_checklists_table";
import TaskCommentsRow from "./task_comments_table";
import TaskLabelAssignmentsRow from "./task_label_assignments_table";
import TaskLogsRow from "./task_logs_table";
import TasksRow from "./tasks_table";
import WebhookDeliveriesRow from "./webhook_deliveries_table";
import WebhookSubscriptionsRow from "./webhook_subscriptions_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  issue_links: __table({
    name: 'issue_links',
    indexes: [
      { accessor: 'kanban_task_id', name: 'issue_links_kanban_task_id_idx_btree', algorithm: 'btree', columns: [
        'kanbanTaskId',
      ] },
    ],
    constraints: [
      { name: 'issue_links_kanban_task_id_key', constraint: 'unique', columns: ['kanbanTaskId'] },
    ],
  }, IssueLinksRow),
  kanban_labels: __table({
    name: 'kanban_labels',
    indexes: [
      { accessor: 'id', name: 'kanban_labels_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'kanban_labels_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KanbanLabelsRow),
  swarm_agents: __table({
    name: 'swarm_agents',
    indexes: [
      { accessor: 'id', name: 'swarm_agents_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'swarm_agents_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SwarmAgentsRow),
  task_checklists: __table({
    name: 'task_checklists',
    indexes: [
      { accessor: 'id', name: 'task_checklists_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'task_checklists_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskChecklistsRow),
  task_comments: __table({
    name: 'task_comments',
    indexes: [
      { accessor: 'id', name: 'task_comments_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'task_comments_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskCommentsRow),
  task_label_assignments: __table({
    name: 'task_label_assignments',
    indexes: [
      { accessor: 'id', name: 'task_label_assignments_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'task_label_assignments_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskLabelAssignmentsRow),
  task_logs: __table({
    name: 'task_logs',
    indexes: [
      { accessor: 'id', name: 'task_logs_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'task_logs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskLogsRow),
  tasks: __table({
    name: 'tasks',
    indexes: [
      { accessor: 'id', name: 'tasks_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tasks_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TasksRow),
  webhook_deliveries: __table({
    name: 'webhook_deliveries',
    indexes: [
      { accessor: 'id', name: 'webhook_deliveries_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'webhook_deliveries_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WebhookDeliveriesRow),
  webhook_subscriptions: __table({
    name: 'webhook_subscriptions',
    indexes: [
      { accessor: 'id', name: 'webhook_subscriptions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'webhook_subscriptions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WebhookSubscriptionsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_checklist_item", AddChecklistItemReducer),
  __reducerSchema("add_comment", AddCommentReducer),
  __reducerSchema("add_label", AddLabelReducer),
  __reducerSchema("add_log", AddLogReducer),
  __reducerSchema("add_task", AddTaskReducer),
  __reducerSchema("add_webhook_subscription", AddWebhookSubscriptionReducer),
  __reducerSchema("agent_heartbeat", AgentHeartbeatReducer),
  __reducerSchema("assign_label_to_task", AssignLabelToTaskReducer),
  __reducerSchema("batch_assign_labels", BatchAssignLabelsReducer),
  __reducerSchema("batch_unassign_labels", BatchUnassignLabelsReducer),
  __reducerSchema("block_task", BlockTaskReducer),
  __reducerSchema("bulk_reorder_tasks", BulkReorderTasksReducer),
  __reducerSchema("claim_task", ClaimTaskReducer),
  __reducerSchema("complete_task", CompleteTaskReducer),
  __reducerSchema("delete_comment", DeleteCommentReducer),
  __reducerSchema("delete_task", DeleteTaskReducer),
  __reducerSchema("link_issue", LinkIssueReducer),
  __reducerSchema("log_webhook_delivery", LogWebhookDeliveryReducer),
  __reducerSchema("register_agent", RegisterAgentReducer),
  __reducerSchema("remove_checklist_item", RemoveChecklistItemReducer),
  __reducerSchema("remove_label", RemoveLabelReducer),
  __reducerSchema("remove_webhook_subscription", RemoveWebhookSubscriptionReducer),
  __reducerSchema("reorder_checklist_items", ReorderChecklistItemsReducer),
  __reducerSchema("reorder_task", ReorderTaskReducer),
  __reducerSchema("seed_sample_tasks", SeedSampleTasksReducer),
  __reducerSchema("set_agent_capabilities", SetAgentCapabilitiesReducer),
  __reducerSchema("set_dependency", SetDependencyReducer),
  __reducerSchema("set_task_score", SetTaskScoreReducer),
  __reducerSchema("set_task_skills", SetTaskSkillsReducer),
  __reducerSchema("toggle_checklist_item", ToggleChecklistItemReducer),
  __reducerSchema("unassign_label_from_task", UnassignLabelFromTaskReducer),
  __reducerSchema("unclaim_task", UnclaimTaskReducer),
  __reducerSchema("unlink_issue", UnlinkIssueReducer),
  __reducerSchema("update_issue_link_status", UpdateIssueLinkStatusReducer),
  __reducerSchema("update_label", UpdateLabelReducer),
  __reducerSchema("update_task", UpdateTaskReducer),
  __reducerSchema("update_webhook_subscription", UpdateWebhookSubscriptionReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.4.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

