// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  IssueLinkStatus,
} from "./types";


export default __t.row({
  kanbanTaskId: __t.string().primaryKey().name("kanban_task_id"),
  issueNumber: __t.u32().name("issue_number"),
  repo: __t.string(),
  issueUrl: __t.string().name("issue_url"),
  htmlUrl: __t.string().name("html_url"),
  get status() {
    return IssueLinkStatus;
  },
  linkedAt: __t.u64().name("linked_at"),
});
