// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SwarmAgentStatus,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  host: __t.string(),
  capabilities: __t.option(__t.string()),
  repoFocus: __t.option(__t.string()).name("repo_focus"),
  currentTaskId: __t.option(__t.string()).name("current_task_id"),
  get status() {
    return SwarmAgentStatus;
  },
  lastHeartbeat: __t.u64().name("last_heartbeat"),
  firstSeen: __t.u64().name("first_seen"),
});
