// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  title: __t.string(),
  description: __t.string(),
  priority: __t.u8(),
  status: __t.string(),
  assignedTo: __t.option(__t.string()).name("assigned_to"),
  repo: __t.string(),
  branch: __t.option(__t.string()),
  roadmapItem: __t.string().name("roadmap_item"),
  createdBy: __t.string().name("created_by"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
  dependsOn: __t.option(__t.string()).name("depends_on"),
});
