// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const IssueLink = __t.object("IssueLink", {
  kanbanTaskId: __t.string(),
  issueNumber: __t.u32(),
  repo: __t.string(),
  issueUrl: __t.string(),
  htmlUrl: __t.string(),
  status: __t.string(),
  linkedAt: __t.u64(),
});
export type IssueLink = __Infer<typeof IssueLink>;

export const KanbanLabel = __t.object("KanbanLabel", {
  id: __t.string(),
  name: __t.string(),
  color: __t.string(),
  description: __t.string(),
  createdAt: __t.u64(),
});
export type KanbanLabel = __Infer<typeof KanbanLabel>;

export const SwarmAgent = __t.object("SwarmAgent", {
  id: __t.string(),
  host: __t.string(),
  capabilities: __t.option(__t.string()),
  repoFocus: __t.option(__t.string()),
  currentTaskId: __t.option(__t.string()),
  status: __t.string(),
  lastHeartbeat: __t.u64(),
  firstSeen: __t.u64(),
});
export type SwarmAgent = __Infer<typeof SwarmAgent>;

export const Task = __t.object("Task", {
  id: __t.string(),
  title: __t.string(),
  description: __t.string(),
  priority: __t.u8(),
  status: __t.string(),
  assignedTo: __t.option(__t.string()),
  repo: __t.string(),
  branch: __t.option(__t.string()),
  roadmapItem: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  dependsOn: __t.option(__t.string()),
  requiredSkills: __t.option(__t.string()),
  score: __t.u32(),
  position: __t.option(__t.u32()),
  failCount: __t.u32(),
  maxAttempts: __t.u32(),
  failReason: __t.option(__t.string()),
  subtaskOf: __t.option(__t.string()),
  subtasks: __t.option(__t.string()),
  dueBy: __t.option(__t.u64()),
  sprint: __t.option(__t.string()),
  archived: __t.bool(),
  estimatedHours: __t.option(__t.u32()),
  spentHours: __t.option(__t.u32()),
});
export type Task = __Infer<typeof Task>;

export const TaskChecklistItem = __t.object("TaskChecklistItem", {
  id: __t.string(),
  taskId: __t.string(),
  text: __t.string(),
  completed: __t.bool(),
  position: __t.u32(),
  createdAt: __t.u64(),
});
export type TaskChecklistItem = __Infer<typeof TaskChecklistItem>;

export const TaskComment = __t.object("TaskComment", {
  id: __t.string(),
  taskId: __t.string(),
  author: __t.string(),
  body: __t.string(),
  createdAt: __t.u64(),
});
export type TaskComment = __Infer<typeof TaskComment>;

export const TaskLabelAssignment = __t.object("TaskLabelAssignment", {
  id: __t.string(),
  taskId: __t.string(),
  labelId: __t.string(),
});
export type TaskLabelAssignment = __Infer<typeof TaskLabelAssignment>;

export const TaskLog = __t.object("TaskLog", {
  id: __t.string(),
  taskId: __t.string(),
  action: __t.string(),
  agentId: __t.option(__t.string()),
  notes: __t.option(__t.string()),
  timestamp: __t.u64(),
});
export type TaskLog = __Infer<typeof TaskLog>;

export const WebhookDelivery = __t.object("WebhookDelivery", {
  id: __t.string(),
  webhookId: __t.string(),
  event: __t.string(),
  url: __t.string(),
  statusCode: __t.u32(),
  responseBody: __t.string(),
  success: __t.bool(),
  deliveredAt: __t.u64(),
});
export type WebhookDelivery = __Infer<typeof WebhookDelivery>;

export const WebhookSubscription = __t.object("WebhookSubscription", {
  id: __t.string(),
  url: __t.string(),
  whType: __t.string(),
  events: __t.string(),
  label: __t.string(),
  createdAt: __t.u64(),
});
export type WebhookSubscription = __Infer<typeof WebhookSubscription>;

