// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Task = __t.object("Task", {
  id: __t.string(),
  title: __t.string(),
  description: __t.string(),
  priority: __t.u8(),
  status: __t.string(),
  assignedTo: __t.option(__t.string()),
  repo: __t.string(),
  branch: __t.option(__t.string()),
  roadmapItem: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  dependsOn: __t.option(__t.string()),
});
export type Task = __Infer<typeof Task>;

export const TaskLog = __t.object("TaskLog", {
  id: __t.string(),
  taskId: __t.string(),
  action: __t.string(),
  agentId: __t.option(__t.string()),
  notes: __t.option(__t.string()),
  timestamp: __t.u64(),
});
export type TaskLog = __Infer<typeof TaskLog>;

