// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ApiKey = __t.object("ApiKey", {
  id: __t.string(),
  keyHash: __t.string(),
  name: __t.string(),
  repoScope: __t.option(__t.string()),
  permissions: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  lastUsedAt: __t.u64(),
  active: __t.bool(),
});
export type ApiKey = __Infer<typeof ApiKey>;

export const AutomationRule = __t.object("AutomationRule", {
  id: __t.string(),
  name: __t.string(),
  description: __t.string(),
  triggerEvent: __t.string(),
  condition: __t.option(__t.string()),
  actionType: __t.string(),
  actionConfig: __t.string(),
  repo: __t.option(__t.string()),
  active: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type AutomationRule = __Infer<typeof AutomationRule>;

export const AutomationRuleLog = __t.object("AutomationRuleLog", {
  id: __t.string(),
  ruleId: __t.string(),
  ruleName: __t.string(),
  triggerEvent: __t.string(),
  taskId: __t.string(),
  actionType: __t.string(),
  result: __t.string(),
  errorMessage: __t.option(__t.string()),
  firedAt: __t.u64(),
});
export type AutomationRuleLog = __Infer<typeof AutomationRuleLog>;

export const DispatcherStateRow = __t.object("DispatcherStateRow", {
  key: __t.string(),
  value: __t.string(),
  updatedAt: __t.u64(),
});
export type DispatcherStateRow = __Infer<typeof DispatcherStateRow>;

export const IssueLink = __t.object("IssueLink", {
  kanbanTaskId: __t.string(),
  issueNumber: __t.u32(),
  repo: __t.string(),
  issueUrl: __t.string(),
  htmlUrl: __t.string(),
  status: __t.string(),
  linkedAt: __t.u64(),
});
export type IssueLink = __Infer<typeof IssueLink>;

export const KanbanLabel = __t.object("KanbanLabel", {
  id: __t.string(),
  name: __t.string(),
  color: __t.string(),
  description: __t.string(),
  createdAt: __t.u64(),
});
export type KanbanLabel = __Infer<typeof KanbanLabel>;

export const KanbanProject = __t.object("KanbanProject", {
  id: __t.string(),
  name: __t.string(),
  description: __t.string(),
  color: __t.string(),
  priority: __t.u8(),
  active: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type KanbanProject = __Infer<typeof KanbanProject>;

export const SchemaMigration = __t.object("SchemaMigration", {
  version: __t.string(),
  description: __t.string(),
  appliedAt: __t.u64(),
  appliedBy: __t.string(),
  checksum: __t.option(__t.string()),
});
export type SchemaMigration = __Infer<typeof SchemaMigration>;

export const SwarmAgent = __t.object("SwarmAgent", {
  id: __t.string(),
  host: __t.string(),
  capabilities: __t.option(__t.string()),
  repoFocus: __t.option(__t.string()),
  currentTaskId: __t.option(__t.string()),
  status: __t.string(),
  lastHeartbeat: __t.u64(),
  firstSeen: __t.u64(),
});
export type SwarmAgent = __Infer<typeof SwarmAgent>;

export const Task = __t.object("Task", {
  id: __t.string(),
  title: __t.string(),
  description: __t.string(),
  priority: __t.u8(),
  status: __t.string(),
  assignedTo: __t.option(__t.string()),
  repo: __t.string(),
  branch: __t.option(__t.string()),
  roadmapItem: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
  dependsOn: __t.option(__t.string()),
  requiredSkills: __t.option(__t.string()),
  score: __t.u32(),
  position: __t.option(__t.u32()),
  failCount: __t.u32(),
  maxAttempts: __t.u32(),
  failReason: __t.option(__t.string()),
  subtaskOf: __t.option(__t.string()),
  subtasks: __t.option(__t.string()),
  dueBy: __t.option(__t.u64()),
  sprint: __t.option(__t.string()),
  archived: __t.bool(),
  estimatedHours: __t.option(__t.u32()),
  spentHours: __t.option(__t.u32()),
});
export type Task = __Infer<typeof Task>;

export const TaskChecklistItem = __t.object("TaskChecklistItem", {
  id: __t.string(),
  taskId: __t.string(),
  text: __t.string(),
  completed: __t.bool(),
  position: __t.u32(),
  createdAt: __t.u64(),
});
export type TaskChecklistItem = __Infer<typeof TaskChecklistItem>;

export const TaskComment = __t.object("TaskComment", {
  id: __t.string(),
  taskId: __t.string(),
  author: __t.string(),
  body: __t.string(),
  createdAt: __t.u64(),
});
export type TaskComment = __Infer<typeof TaskComment>;

export const TaskLabelAssignment = __t.object("TaskLabelAssignment", {
  id: __t.string(),
  taskId: __t.string(),
  labelId: __t.string(),
});
export type TaskLabelAssignment = __Infer<typeof TaskLabelAssignment>;

export const TaskLog = __t.object("TaskLog", {
  id: __t.string(),
  taskId: __t.string(),
  action: __t.string(),
  agentId: __t.option(__t.string()),
  notes: __t.option(__t.string()),
  timestamp: __t.u64(),
});
export type TaskLog = __Infer<typeof TaskLog>;

export const TaskRelation = __t.object("TaskRelation", {
  id: __t.string(),
  taskId: __t.string(),
  relatedTaskId: __t.string(),
  relationType: __t.string(),
  createdAt: __t.u64(),
});
export type TaskRelation = __Infer<typeof TaskRelation>;

export const TaskTemplate = __t.object("TaskTemplate", {
  id: __t.string(),
  title: __t.string(),
  description: __t.string(),
  priority: __t.u8(),
  repo: __t.string(),
  roadmapItem: __t.string(),
  requiredSkills: __t.option(__t.string()),
  cronSchedule: __t.string(),
  createdBy: __t.string(),
  createdAt: __t.u64(),
  lastTriggeredAt: __t.u64(),
  active: __t.bool(),
});
export type TaskTemplate = __Infer<typeof TaskTemplate>;

export const WebhookDelivery = __t.object("WebhookDelivery", {
  id: __t.string(),
  webhookId: __t.string(),
  event: __t.string(),
  url: __t.string(),
  statusCode: __t.u32(),
  responseBody: __t.string(),
  success: __t.bool(),
  deliveredAt: __t.u64(),
});
export type WebhookDelivery = __Infer<typeof WebhookDelivery>;

export const WebhookSubscription = __t.object("WebhookSubscription", {
  id: __t.string(),
  url: __t.string(),
  whType: __t.string(),
  events: __t.string(),
  label: __t.string(),
  createdAt: __t.u64(),
});
export type WebhookSubscription = __Infer<typeof WebhookSubscription>;

