// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  ruleId: __t.string(),
  name: __t.string(),
  description: __t.string(),
  triggerEvent: __t.string(),
  condition: __t.string(),
  actionType: __t.string(),
  actionConfig: __t.string(),
  repo: __t.string(),
  active: __t.bool(),
};
