// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  title: __t.string(),
  description: __t.string(),
  priority: __t.u8(),
  repo: __t.string(),
  roadmapItem: __t.string(),
  requiredSkills: __t.string(),
  cronSchedule: __t.string(),
  active: __t.bool(),
};
