// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  webhookId: __t.string().name("webhook_id"),
  event: __t.string(),
  url: __t.string(),
  statusCode: __t.u32().name("status_code"),
  responseBody: __t.string().name("response_body"),
  success: __t.bool(),
  deliveredAt: __t.u64().name("delivered_at"),
});
